# What is Numpy?
Numpy stands for Numerical Python.<br>
Numpy is the core library for scientific computing in Python.<br>
It provides a high-performance multidimensional array object, and tools for working with these arrays.
To use Numpy, we first need to import the `numpy` package:

In [1]:
!pip install numpy
#Used to install a package which is not present in colab by default. However, numpy is preinstalled by default

In [2]:
import numpy as np
#will import the numpy library and we can access it as np.

#Array  
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.<br>
It is similar to lists in python,but much more powerful!

In [4]:
#Let's create an array using numpy :)
arr = np.array([1, 2, 3, 4, 5])
#will create a 1-dimensional array having value [1, 2, 3, 4, 5]
print(arr)

[1 2 3 4 5]


###Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [9]:
#->Indexing/accessing elements of array:
#indexing starts form 0; first element is 0-index, second element is 1-index and so on...
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])
print(arr[2])
print(arr[1], arr[2])

2
3
2 3


In [10]:
#We can also change elements of an array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[2] = 70
print(arr)

[ 1  2 70  4  5  6  7]


# Higher Dimensional arrays

In [16]:
# 2-dimensional arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)  #(2, 3) because it has 2 rows and 3 columns
print(arr.ndim)   #prints the dimension of the array
print(arr.dtype)  #prints the data type of the array
print(arr.size)   #prints the number of elements in the array
print(arr[0][2])  #prints the third element from the first row, as the row and column indexing begins from 0.

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6
3


# Generating some standard Arrays

In [18]:
#zero array (having zero as all its elements)
b = np.zeros((3, 5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#generating a random array
m = np.random.randn(3, 4)
print(m)

[[ 1.01368083  0.13678307  0.83811217 -0.72101249]
 [-0.58399123  0.48998809  0.78117902 -0.05235399]
 [-1.20004606 -1.00239762  1.18185143 -1.14940367]]


In [22]:
#generating an array containing 1 as all its elements
n = np.ones((3, 2))
print(n)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
#arange function wil generate an array from 0 to n-1
p = np.arange(5)
print(p)

[0 1 2 3 4]


In [27]:
#generate evenly spaced numbers over a specified interval.
#Syntax: array_name=np.linspace(start,end,num)

arr = np.linspace(0, 10, 10)

print(arr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


##Numpy Array Slicing
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].It will give elements from start index to end-1.<br>
We can also define the step, like this: [start:end:step].(steps =number of jumps)

In [28]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:5])
print(arr[0:5:2])   #also uses the step
print(arr[:5])
print(arr[2:])

[2 3 4 5]
[1 3 5]
[1 2 3 4 5]
[3 4 5]


In [35]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
print(a[0:1, 1:3])
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[2 3]]
2


# Changing the dinemsion of the array

In [41]:
#2-D to 3-D
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ndmin = 3)
print(a)
print('number of dimensions:', a.ndim)
print(a.dtype)
#similarly you can do for other arrays, and check it.

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
number of dimensions: 3
int64


##Array Mathematics using Numpy
Numpy offers a lot of functions to perform mathematical calculations involving high-dimensional arrays very efficiently!

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.random.randn(2, 3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 1.07351326 -0.89104323 -1.19875272]
 [-0.3874671   0.36833643 -1.06939242]]


In [44]:
#Sum of each element of respective array
print(np.sum(a))
print(np.sum(b))

21
-2.104805782974001


In [45]:
#Matrix addition
c = a + b
print(c)

[[2.07351326 1.10895677 1.80124728]
 [3.6125329  5.36833643 4.93060758]]


In [48]:
#transpose of matrix
print(np.transpose(a))
print(np.transpose(a).shape)    #a originally had a shape of (2, 3) => (3, 2)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [50]:
#Element wise multiplication
d = np.multiply(a, b)
print(d)

[[ 1.07351326 -1.78208645 -3.59625817]
 [-1.5498684   1.84168214 -6.41635453]]


In [55]:
#matrix multiplication
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
f = np.array([[1, 2], [3, 4], [5, 6]])
print(np.matmul(e, f))

[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [56]:
l = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m = np.random.randn(3, 3)
print(l)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0.83082486 -1.24660468  0.23743107]
 [ 0.58982165  0.69870213  0.06828563]
 [ 2.38510842 -0.13246684  0.27942497]]


In [58]:
o = np.dot(l, m)
q = np.dot(m, l)
print(o)
print(q)

[[ 9.16579344 -0.24660093  1.21227724]
 [20.58305825 -2.28770909  2.96770224]
 [32.00032307 -4.32881725  4.72312724]]
[[-2.49357638 -2.67192513 -2.85027388]
 [ 3.86262961  5.21943902  6.57624844]
 [ 3.81121584  6.34328239  8.87534894]]


In [68]:
#finding the maximum element in an array or any nested array
temp = np.array([[1, 2], [3, 55], [5, 6]])
print(np.max(temp))

55


In [69]:
print(temp)

[[ 1  2]
 [ 3 55]
 [ 5  6]]


In [72]:
#finding the row containing the maximum element
print(np.max(temp, axis = 0))

[ 5 55]


In [71]:
#finding the column containing the maximum element
print(np.max(temp, axis = 1))

[ 2 55  6]


# Pandas:


*   pyhton library used for working with data sets.
*   has functions for analyzing, cleaning, exploring and manipulating data.



In [73]:
import pandas as pd

# Creating a Dataframe

what is a dataframe??


*   A Pandas dataframe is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.



In [74]:
#Create a dataframe
#Dictionary of key value pair called data
data = {"Subject": ["Mathematics", "Physics", "Chemistry"], "Marks": [90, 80, 70]}

#Calling the the pandas data frame method bys passing the dictioonary (data) as a parameter
df = pd.DataFrame(data)
df

Subject  Marks
0  Mathematics     90
1      Physics     80
2    Chemistry     70

# Some basic operations in Pandas

In [79]:
#Use loc
print(df.loc[0]) #returns the 0 indexed data

Subject    Mathematics
Marks               90
Name: 0, dtype: object


In [80]:
#Selecting multiple rows
print(df.loc[[0, 1]])

       Subject  Marks
0  Mathematics     90
1      Physics     80


In [83]:
#selecting columns
df[["Subject"]]

Subject
0  Mathematics
1      Physics
2    Chemistry

###Adding new columns
Use df.insert().

In [84]:
#syntax: df.insert(index, name_of_col, list_of_values)

df.insert(2, "Grade", ["A+", "A", "B"])

In [85]:
df

Subject  Marks Grade
0  Mathematics     90    A+
1      Physics     80     A
2    Chemistry     70     B

In [90]:
#Adding new rows to the dataframe
df2 = {'Subject': 'General Studies', 'Marks': 85, 'Grade': 'A'}
# New row as a dataframe
df2 = pd.DataFrame([{'Subject': 'General Studies', 'Marks': 85, 'Grade': 'A'}])

# Append using pd.concat()
df = pd.concat([df, df2], ignore_index=True)

print(df)

           Subject  Marks Grade
0      Mathematics     90    A+
1          Physics     80     A
2        Chemistry     70     B
3  General Studies     85     A
4  General Studies     85     A


In [92]:
#Deleting column
del df["Grade"]

KeyError: 'Grade'

In [93]:
df

Subject  Marks
0      Mathematics     90
1          Physics     80
2        Chemistry     70
3  General Studies     85
4  General Studies     85

In [ ]:
#saving the dataframe as a csv file
df.to_csv('quiz_marks.csv',index=False)

In [ ]:
#save file as excel
df.to_excel('quiz_marks.xlsx',index=False)

In [ ]:
#Loading a csv file
temp=pd.read_csv('quiz_marks.csv')
temp

In [ ]:
#loading an excel file

ex=pd.read_excel('quiz_marks.xlsx')
ex